DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);


CREATE TABLE post (
    id int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    img TEXT DEFAULT NULL,
    body TEXT NOT NULL,
    Foreign Key (author_id) REFERENCES users (id)
);
